import React, { createContext, useState, useEffect } from 'react';

export const LanguageContext = createContext();

export const translations = {
  fr: {
    // Navigation & Common
    app_title: "neostock",
    home: "Accueil",
    dashboard: "Tableau de bord",
    market_b2b: "Marché B2B Live",
    products: "Produits",
    predictions: "Prédictions IA",
    transactions: "Transactions",
    view_landing: "Voir la Landing Page",
    login: "Se connecter",
    logout: "Déconnexion",
    quick_login: "Se connecter en 1 Clic →",
    demo_ready: "Compte Prêt à l'Emploi",
    access_app: "Accéder au Dashboard",
    support_phone: "+216 58 026 163",
    support_tagline: "🇹🇳 Solution IA d'approvisionnement & gestion de stock pour le commerce tunisien",
    refresh: "Actualiser",
    cancel: "Annuler",
    save: "Sauvegarder",

    // Landing Page
    hero_badge: "Votre magasin perd de l'argent chaque jour",
    hero_title_1: "Voyez où part votre argent —",
    hero_title_2: "et arrêtez la rupture.",
    hero_sub: "Ruptures de stock sur les produits phares, écarts de caisse, surstock dormant : neostock combine l'IA Google Gemini 2.5 Flash et la formule EOQ pour anticiper vos approvisionnements en temps réel.",
    hero_today: "Aujourd'hui • Tunis",
    hero_profit: "Profit estimé du jour",
    hero_rupture: "Couscous Randa 1kg",
    hero_alert: "Harissa Le Phare",

    // Calculator
    calc_kicker: "Calculateur de pertes",
    calc_title: "Combien votre commerce perd-il chaque mois ?",
    calc_sub: "Faites glisser pour estimer. La rupture de stock et la démarque représentent en moyenne 1.5 % à 4 % du chiffre d'affaires.",
    calc_rev: "Chiffre d'affaires mensuel",
    calc_rate: "Taux de perte / rupture estimé",
    calc_lost: "Ce que vous perdez aujourd'hui :",
    calc_recovered: "Ce que neostock vous fait récupérer :",
    calc_per_month: "/ mois",
    calc_per_year: "/ an",
    calc_cta: "Récupérer cet argent → Démo en 1 clic",

    // 3 Problems
    prob_kicker: "Le vrai problème",
    prob_title: "Les trois façons dont votre magasin perd de l'argent",
    prob_sub: "Sans que vous ne vous en rendiez compte. Chaque jour.",
    prob_1_tag: "LES RUPTURES",
    prob_1_title: "La rupture de stock",
    prob_1_quote: "« Chaque produit manquant sur vos étagères, c'est une vente perdue et un client qui file chez le voisin. »",
    prob_2_tag: "LE SURSTOCK",
    prob_2_title: "Le capital gelé",
    prob_2_quote: "« L'argent qui dort dans des cartons qui ne tournent pas, c'est de la trésorerie bloquée inutilement. »",
    prob_3_tag: "LA DÉMARQUE & PRIX",
    prob_3_title: "Les écarts imprévus",
    prob_3_quote: "« Les pertes et invendus ne sont découverts qu'au comptage de fin d'année, quand il est trop tard. »",

    // B2B Section
    b2b_kicker: "Mercuriale Nationale Live • Tunisie 🇹🇳",
    b2b_title: "Marché de Gros & Stocks B2B en Direct",
    b2b_sub: "Suivez les cours de gros en temps réel et mutualisez vos achats pour obtenir jusqu'à -20% de remise d'usine.",
    b2b_cta: "Accéder au Terminal Marché B2B",
    b2b_pools_title: "Groupements d'Achats B2B Actifs",
    b2b_pools_sub: "Mutualisez avec 56 épiceries tunisiennes partenaires",
    b2b_join_pool: "Rejoindre un Pool d'Achat →",

    // Dashboard
    dash_loading: "Chargement du tableau de bord neostock...",
    dash_header: "Tableau de Bord neostock",
    dash_market: "Marché de Détail Tunisien",
    dash_refresh: "Actualiser",
    dash_assistant_btn: "Assistant & RAG IA",
    kpi_products: "Total Produits",
    kpi_products_sub: "Articles en catalogue",
    kpi_alerts: "Alertes Stock",
    kpi_alerts_sub: "Niveau critique ou bas",
    kpi_value: "Valeur Stock",
    kpi_value_sub: "Valeur d'achat totale",
    kpi_suggested: "Commandes Suggérées",
    kpi_suggested_sub: "Optimisation EOQ",
    sim_title: "Module d'Analyse Produit & Recommandation IA",
    sim_sub: "Saisissez ou modifiez les données d'un produit pour obtenir l'arbitrage IA instantané",
    sim_select: "Sélectionner un produit :",
    sim_new: "➕ Nouveau Produit...",
    sim_name: "Nom du Produit",
    sim_stock: "Stock Actuel",
    sim_buy_price: "Prix d'Achat (TND)",
    sim_daily_sales: "Ventes par Jour (Moyenne)",
    sim_lead: "Délai Fournisseur (Jours)",
    sim_min_stock: "Stock Seuil Minimum",
    sim_supplier: "Fournisseur Principal",
    sim_calc_btn: "Recommander IA",
    sim_calculating: "Calcul...",
    sim_save_btn: "Sauver",
    sim_saved_success: "sauvegardé avec succès !",
    rec_title: "Recommandation neostock IA",
    risk_critical: "🔴 RISQUE DE RUPTURE",
    risk_warning: "🟠 ATTENTION",
    risk_success: "🟢 STOCK SUFFISANT",
    risk_critical_msg: "Le stock actuel est estimé à environ",
    risk_critical_sub: "Il y aura rupture avant réception si vous ne commandez pas dès maintenant !",
    risk_warning_msg: "Le stock commence à devenir faible (couverture estimée :",
    risk_warning_sub: "Préparez un bon de commande préventif.",
    risk_success_msg: "Aucune commande urgente nécessaire (couverture estimée :",
    days_unit: "jours",
    lead_time_label: "Délai fournisseur :",
    eoq_title: "Calcul Économique de Commande (EOQ)",
    eoq_qty: "Quantité recommandée :",
    eoq_units: "unités",
    eoq_cost: "Coût estimé :",
    btn_whatsapp: "💬 Bon WhatsApp",
    btn_b2b: "Passer Bon B2B",
    stat_daily_demand: "Demande/Jour",
    stat_monthly_demand: "Demande/Mois",
    stat_margin: "Marge Brute",
    stat_turnover: "Rotation Stock",
    stat_safety_stock: "Stock Sécurité",
    stat_reorder_point: "Point Commande",
    ai_forecast_title: "📊 Prévision IA — Mois Prochain",
    ai_forecast_units: "unités prévues",
    ai_confidence: "Confiance",
    ai_season: "Saison :",
    ai_review_title: "🧠 Avis IA",
    chart_title: "Niveaux de Stock par Produit",
    chart_items: "articles",
    alerts_title: "Alertes Ravitaillement",
    alerts_urgent: "urgentes",
    alerts_empty: "Tous vos stocks sont au-dessus du seuil minimum. Bravo !",
    alerts_assistant_link: "Consulter l'Assistant IA & Calendrier →",

    // Market Intelligence Page (/market)
    market_title: "Marché de Gros & Stocks B2B",
    market_subtitle: "Cours de référence Bir El Kassâa, Sfax & Centrales d'Achat • Données réelles",
    market_tag: "Terminal B2B Live",
    market_origin_label: "Mercuriale Nationale Tunisienne 🇹🇳",
    refresh_quotes: "Actualiser les Cours",
    gemini_btn: "Analyse IA Gemini 2.5",
    gemini_analyzing: "Analyse Gemini...",
    price_index: "Indice des Prix",
    quota_products: "Produits sous Quota",
    quota_commodities: "2 denrées",
    quota_names: "Lait & Café",
    season_opp: "Opportunité Saison",
    season_name: "Dattes Deglet",
    season_badge: "-8.6% récolte",
    active_pools: "Pools d'Achats Actifs",
    pools_count: "groupements",
    pools_discount: "Jusqu'à -20%",
    bulletin_title: "Bulletin Stratégique de Marché B2B",
    bulletin_sub: "Généré en direct selon les cours grossistes tunisiens",
    stance: "Posture :",
    deals_title: "Groupements d'Achat B2B en Cours",
    deals_factory_price: "Prix d'usine direct",
    deals_sub: "Mutualisez vos volumes avec les commerces voisins pour réduire vos coûts d'achat",
    deal_savings: "Économie",
    deal_fill: "Remplissage du lot :",
    deal_remaining: "Reste",
    deal_stores: "commerces",
    deal_joined: "Rejoint",
    deal_join_btn: "Participer",
    deal_alert_success: "Vous avez rejoint le pool ! Vos commandes seront groupées pour économiser au tarif usine.",
    mercuriale_title: "Mercuriale & Tendance des Prix de Gros (Tunisie)",
    mercuriale_sub: "Prix constatés sur le marché de gros central & grossistes de région",
    cat_all: "Tous les produits",
    cat_cereals: "Céréales & Dérivés",
    cat_hot_drinks: "Boissons Chaudes",
    cat_oils: "Huiles & Graisses",
    cat_dairy: "Produits Laitiers",
    cat_fruits: "Fruits Secs & Frais",
    cat_drinks: "Boissons",
    th_product_spec: "Produit & Spécification",
    th_origin_supplier: "Origine / Fournisseur",
    th_wholesale_price: "Prix de Gros (TND)",
    th_month_trend: "Tendance Mois",
    th_availability: "Disponibilité",
    th_recommendation: "Recommandation Stratégique",
    th_action: "Action B2B",
    prev_label: "Précédent :",
    btn_wholesaler: "Grossiste",
    status_available: "Disponible",
    status_tension: "Sous Tension",
    status_restricted: "Quotas Restreints",
    status_new_arrival: "Arrivage Nouveau",
    status_surplus: "Surstock Grossiste",
    status_moderate: "Modérée",

    // Products Page (/products)
    prod_title: "neostock — Inventaire",
    prod_sub: "Suivi des stocks, prix d'achat/vente et fournisseurs tunisiens",
    new_product: "Nouveau Produit",
    search_placeholder: "Rechercher par nom, catégorie (ex: condiments, grains) ou fournisseur...",
    col_product: "Produit",
    col_category: "Catégorie",
    col_stock: "Stock Actuel",
    col_buy_price: "Prix Achat",
    col_sell_price: "Prix Vente",
    col_supplier: "Fournisseur",
    col_status: "Statut",
    col_actions: "Actions",
    status_critical: "Critique",
    status_low: "Bas",
    status_sufficient: "Suffisant",
    modal_add_title: "Ajouter un Nouveau Produit",
    modal_cancel: "Annuler",
    modal_create: "Créer le Produit",
    prod_loading: "Chargement des données...",
    prod_empty: "Aucun produit ne correspond à la recherche.",
    prod_confirm_delete: "Voulez-vous vraiment supprimer cet article de l'inventaire ?",
    prod_created_success: "ajouté avec succès !",

    // Predictions Page (/predictions)
    pred_title: "neostock — Prédictions & IA",
    pred_sub: "Moteur prédictif alimenté par Google Gemini et le calendrier tunisien",
    pred_select_label: "Sélectionner un produit à analyser :",
    pred_btn_analyze: "Lancer l'Arbitrage IA",
    pred_analyzing: "Analyse en cours...",
    pred_chart_title: "Historique des Ventes & Prévision",
    pred_chart_sub: "Données réelles des 12 derniers mois + Projection IA",
    pred_metrics_title: "Métriques Clés & Recommandation d'Approvisionnement",
    pred_next_month: "Mois Prochain 🔮",
    pred_sales_legend: "Ventes Réelles",
    pred_forecast_legend: "Prévision IA",

    // Transactions Page (/transactions)
    trx_title: "neostock — Historique des Transactions",
    trx_sub: "Bons de commandes grossistes, réceptions et décaissements",
    trx_new_btn: "Nouvelle Commande Grossiste",
    trx_total_spent: "Total Dépensé (B2B)",
    trx_count: "Nombre de Commandes",
    trx_avg_order: "Panier Moyen Appro",
    trx_col_id: "Réf",
    trx_col_date: "Date",
    trx_col_product: "Produit",
    trx_col_qty: "Quantité",
    trx_col_unit_cost: "Coût Unitaire",
    trx_col_total: "Total (TND)",
    trx_col_supplier: "Grossiste",
    trx_col_status: "Statut",
    trx_filter_all: "Toutes",
    trx_filter_delivered: "Livrées",
    trx_filter_pending: "En attente",
    trx_modal_title: "Enregistrer un Bon de Commande B2B",
    trx_status_delivered: "Livré",
    trx_status_pending: "En attente"
  },
  en: {
    // Navigation & Common
    app_title: "neostock",
    home: "Home",
    dashboard: "Dashboard",
    market_b2b: "Live B2B Market",
    products: "Products",
    predictions: "AI Predictions",
    transactions: "Transactions",
    view_landing: "View Landing Page",
    login: "Sign In",
    logout: "Sign Out",
    quick_login: "1-Click Sign In →",
    demo_ready: "Ready-to-Use Account",
    access_app: "Access Dashboard",
    support_phone: "+216 58 026 163",
    support_tagline: "🇹🇳 AI Inventory & Supply Optimization Solution for Retail",
    refresh: "Refresh",
    cancel: "Cancel",
    save: "Save",

    // Landing Page
    hero_badge: "Your store is losing money every single day",
    hero_title_1: "See where your money goes —",
    hero_title_2: "and stop the stockout.",
    hero_sub: "Stockouts on top-selling items, cash gaps, dead stock: neostock combines Google Gemini 2.5 Flash AI and the EOQ formula to forecast demand and stop losses in real time.",
    hero_today: "Today • Tunis",
    hero_profit: "Estimated daily profit",
    hero_rupture: "Couscous Randa 1kg",
    hero_alert: "Harissa Le Phare",

    // Calculator
    calc_kicker: "Loss Calculator",
    calc_title: "How much does your store lose every month?",
    calc_sub: "Slide to estimate. Stockouts and shrinkage represent on average 1.5% to 4% of total retail turnover.",
    calc_rev: "Monthly Revenue",
    calc_rate: "Estimated Loss / Shrinkage Rate",
    calc_lost: "What you lose today:",
    calc_recovered: "What neostock recovers for you:",
    calc_per_month: "/ month",
    calc_per_year: "/ year",
    calc_cta: "Recover this money → 1-Click Demo",

    // 3 Problems
    prob_kicker: "The Real Problem",
    prob_title: "The Three Ways Your Store Loses Money",
    prob_sub: "Without you even noticing. Every day.",
    prob_1_tag: "STOCKOUTS",
    prob_1_title: "Out-of-Stock Losses",
    prob_1_quote: "“Every missing product on your shelves is a lost sale and a customer going straight to your competitor.”",
    prob_2_tag: "OVERSTOCK",
    prob_2_title: "Frozen Capital",
    prob_2_quote: "“Money tied up in boxes that don't rotate is cash trapped needlessly.”",
    prob_3_tag: "SHRINKAGE & GAP",
    prob_3_title: "Unexpected Gaps",
    prob_3_quote: "“Losses and dead items are only discovered during year-end inventory, when it's too late.”",

    // B2B Section
    b2b_kicker: "Live National Wholesale Feed • Tunisia 🇹🇳",
    b2b_title: "Wholesale Market & Live B2B Stocks",
    b2b_sub: "Track real-time wholesale commodity benchmarks and pool your purchases to get up to -20% factory discounts.",
    b2b_cta: "Access B2B Market Terminal",
    b2b_pools_title: "Active B2B Purchasing Pools",
    b2b_pools_sub: "Pool orders with 56 partner grocery stores",
    b2b_join_pool: "Join a Purchasing Pool →",

    // Dashboard
    dash_loading: "Loading neostock dashboard...",
    dash_header: "neostock Dashboard",
    dash_market: "Tunisian Retail Market",
    dash_refresh: "Refresh",
    dash_assistant_btn: "AI Assistant & RAG",
    kpi_products: "Total Products",
    kpi_products_sub: "Catalog items",
    kpi_alerts: "Stock Alerts",
    kpi_alerts_sub: "Critical or low level",
    kpi_value: "Stock Value",
    kpi_value_sub: "Total purchase value",
    kpi_suggested: "Suggested Orders",
    kpi_suggested_sub: "EOQ Optimization",
    sim_title: "Product Analysis & AI Recommendation Module",
    sim_sub: "Enter or modify product data to get instant AI economic arbitration",
    sim_select: "Select a product:",
    sim_new: "➕ New Product...",
    sim_name: "Product Name",
    sim_stock: "Current Stock",
    sim_buy_price: "Buy Price (TND)",
    sim_daily_sales: "Daily Sales (Average)",
    sim_lead: "Supplier Lead Time (Days)",
    sim_min_stock: "Minimum Stock Threshold",
    sim_supplier: "Main Supplier",
    sim_calc_btn: "Get AI Advice",
    sim_calculating: "Calculating...",
    sim_save_btn: "Save",
    sim_saved_success: "saved successfully!",
    rec_title: "neostock AI Recommendation",
    risk_critical: "🔴 CRITICAL STOCKOUT RISK",
    risk_warning: "🟠 WARNING: LOW STOCK",
    risk_success: "🟢 SUFFICIENT STOCK",
    risk_critical_msg: "Current stock is estimated at approx",
    risk_critical_sub: "Stockout will occur before delivery unless you order now!",
    risk_warning_msg: "Stock is getting low (estimated coverage:",
    risk_warning_sub: "Prepare a preventive purchase order.",
    risk_success_msg: "No urgent reorder needed (estimated coverage:",
    days_unit: "days",
    lead_time_label: "Supplier lead time:",
    eoq_title: "Economic Order Quantity (EOQ)",
    eoq_qty: "Recommended quantity:",
    eoq_units: "units",
    eoq_cost: "Estimated cost:",
    btn_whatsapp: "💬 WhatsApp PO",
    btn_b2b: "Place B2B Order",
    stat_daily_demand: "Daily Demand",
    stat_monthly_demand: "Monthly Demand",
    stat_margin: "Gross Margin",
    stat_turnover: "Stock Turnover",
    stat_safety_stock: "Safety Stock",
    stat_reorder_point: "Reorder Point",
    ai_forecast_title: "📊 AI Forecast — Next Month",
    ai_forecast_units: "forecasted units",
    ai_confidence: "Confidence",
    ai_season: "Season:",
    ai_review_title: "🧠 AI Review",
    chart_title: "Stock Levels by Product",
    chart_items: "items",
    alerts_title: "Restock Alerts",
    alerts_urgent: "urgent",
    alerts_empty: "All your inventory levels are above the minimum threshold. Great job!",
    alerts_assistant_link: "Check AI Assistant & Calendar →",

    // Market Intelligence Page (/market)
    market_title: "Wholesale Market & Live B2B Stocks",
    market_subtitle: "Benchmark prices from Bir El Kassâa, Sfax & Central Purchasing • Real data",
    market_tag: "Live B2B Terminal",
    market_origin_label: "Tunisian National Commodity Board 🇹🇳",
    refresh_quotes: "Refresh Prices",
    gemini_btn: "Gemini 2.5 AI Analysis",
    gemini_analyzing: "Gemini Analyzing...",
    price_index: "Price Index",
    quota_products: "Quoted / Restricted Goods",
    quota_commodities: "2 commodities",
    quota_names: "Milk & Coffee",
    season_opp: "Seasonal Opportunity",
    season_name: "Deglet Dates",
    season_badge: "-8.6% harvest",
    active_pools: "Active Buying Pools",
    pools_count: "pools",
    pools_discount: "Up to -20%",
    bulletin_title: "Strategic B2B Market Bulletin",
    bulletin_sub: "Generated live based on Tunisian wholesale benchmarks",
    stance: "Stance:",
    deals_title: "Active B2B Group Buying Deals",
    deals_factory_price: "Direct factory pricing",
    deals_sub: "Pool your orders with neighboring stores to slash purchase costs",
    deal_savings: "Savings",
    deal_fill: "Pool fulfillment:",
    deal_remaining: "Left",
    deal_stores: "stores",
    deal_joined: "Joined",
    deal_join_btn: "Join Deal",
    deal_alert_success: "You joined the pool! Your orders will be grouped for factory discounts.",
    mercuriale_title: "Wholesale Price Benchmark & Trends (Tunisia)",
    mercuriale_sub: "Observed prices at central wholesale market & regional suppliers",
    cat_all: "All products",
    cat_cereals: "Grains & Pasta",
    cat_hot_drinks: "Hot Beverages",
    cat_oils: "Oils & Fats",
    cat_dairy: "Dairy Products",
    cat_fruits: "Dry & Fresh Fruits",
    cat_drinks: "Beverages",
    th_product_spec: "Product & Specification",
    th_origin_supplier: "Origin / Supplier",
    th_wholesale_price: "Wholesale Price (TND)",
    th_month_trend: "Monthly Trend",
    th_availability: "Availability",
    th_recommendation: "Strategic Recommendation",
    th_action: "B2B Action",
    prev_label: "Previous:",
    btn_wholesaler: "Wholesaler",
    status_available: "Available",
    status_tension: "High Tension",
    status_restricted: "Restricted Quotas",
    status_new_arrival: "New Arrival",
    status_surplus: "Wholesaler Surplus",
    status_moderate: "Moderate",

    // Products Page (/products)
    prod_title: "neostock — Inventory",
    prod_sub: "Stock tracking, purchase/sale pricing & Tunisian suppliers",
    new_product: "New Product",
    search_placeholder: "Search by name, category (e.g. condiments, grains) or supplier...",
    col_product: "Product",
    col_category: "Category",
    col_stock: "Current Stock",
    col_buy_price: "Buy Price",
    col_sell_price: "Sell Price",
    col_supplier: "Supplier",
    col_status: "Status",
    col_actions: "Actions",
    status_critical: "Critical",
    status_low: "Low",
    status_sufficient: "Sufficient",
    modal_add_title: "Add New Product",
    modal_cancel: "Cancel",
    modal_create: "Create Product",
    prod_loading: "Loading data...",
    prod_empty: "No products match the search query.",
    prod_confirm_delete: "Are you sure you want to delete this inventory item?",
    prod_created_success: "added successfully!",

    // Predictions Page (/predictions)
    pred_title: "neostock — AI Predictions",
    pred_sub: "Predictive engine powered by Google Gemini & Tunisian retail seasonality",
    pred_select_label: "Select product to analyze:",
    pred_btn_analyze: "Run AI Demand Arbitration",
    pred_analyzing: "Analyzing...",
    pred_chart_title: "Sales History & Forecast",
    pred_chart_sub: "Past 12 months actual sales + AI projection",
    pred_metrics_title: "Key Metrics & Reorder Recommendation",
    pred_next_month: "Next Month 🔮",
    pred_sales_legend: "Actual Sales",
    pred_forecast_legend: "AI Forecast",

    // Transactions Page (/transactions)
    trx_title: "neostock — Transaction History",
    trx_sub: "Wholesale purchase orders, receipts and cash disbursements",
    trx_new_btn: "New Wholesale Order",
    trx_total_spent: "Total Spent (B2B)",
    trx_count: "Total Orders",
    trx_avg_order: "Average Order Size",
    trx_col_id: "Ref",
    trx_col_date: "Date",
    trx_col_product: "Product",
    trx_col_qty: "Quantity",
    trx_col_unit_cost: "Unit Cost",
    trx_col_total: "Total (TND)",
    trx_col_supplier: "Wholesaler",
    trx_col_status: "Status",
    trx_filter_all: "All",
    trx_filter_delivered: "Delivered",
    trx_filter_pending: "Pending",
    trx_modal_title: "Record B2B Purchase Order",
    trx_status_delivered: "Delivered",
    trx_status_pending: "Pending"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('neostock_lang') || 'fr';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('neostock_lang', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['fr']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
